Ignore Error Message if Not IPython
llnl/hatchet pull request #147
Opened 2024-07-31 18:20 UTC by michaelmckinsey1

https://github.com/LLNL/hatchet/pull/127 introduced a bug where the error message

```
Warning: Roundtrip module could not be loaded. Requires jupyter notebook version <= 7.x.
```

will always print if the `IPython` module is installed, even when running outside of `IPython`, such as when running hatchet in a terminal.

This PR fixes the bug by not printing the error message if [IPython is not registered](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.getipython.html#IPython.core.getipython.get_ipython).

2024-08-01 20:19 UTC, cscully-allison approved these changes
This looks good to me. The 'not isinstance()' check leading into the print can be a little confusing as we are printing in the positive case that there is a Python object. However I acknowledge that this is the best compact 1-line way to write it and only takes a second to understand.

2024-09-03 19:08 UTC, ilumsden requested changes
Besides the one comment on checking for `None`, this looks good. Just the one simple change, and then I'll accept.

2024-09-03 19:08 UTC, ilumsden commented on hatchet/external/__init__.py
> +    if not isinstance(IPython.get_ipython(), type(None)):
Change to this:
```python
if IPython.get_ipython() is not None:
```

2024-09-03 22:04 UTC, michaelmckinsey1 commented on hatchet/external/__init__.py
> +    if not isinstance(IPython.get_ipython(), type(None)):
a965961

2024-09-04 17:12 UTC, ilumsden approved these changes
LGTM

2024-10-29 17:34 UTC, merged